### ISSUE TITLE
MAC OS -> xdialog with dearpygui crashed

### ISSUE THREAD

**Issue by qizheng-1998** [xMGZx/xdialog#10]
When I use the xdialog with dearpygui in MAC, it crashed. It does not happen when running dearpygui on Windows and Linux. And when running xdialog without dearpygui in MAC, it works fine too. 

Below is the program that crashed when "Update Series" button is clicked, where the xdialog.warning is called.

Thank you in advanced!

```py
import dearpygui.dearpygui as dpg
from math import sin, cos
from random import random
import xdialog
dpg.create_context()

def update_series():
    for loop in range(50):
        cosdatax = []
        cosdatay = []
        for i in range(0, 500):
            cosdatax.append(i / 1000)
            randomNum = random()
            cosdatay.append(0.5 + randomNum * cos(50 * i / 1000))
        dpg.set_value('series_tag', [cosdatax, cosdatay])
        dpg.set_item_label('series_tag', "0.5 + "+str(randomNum)+" * cos(x)")

    xdialog.warning("warning", "warning")

sindatax = []
sindatay = []
for i in range(0, 500):
    sindatax.append(i )
    sindatay.append(0.5 + 0.5 * sin(50 * i / 1000))


with dpg.window(label="Tutorial", tag="win"):
    with dpg.group(horizontal = True):
        dpg.add_button(label="Update Series", callback=update_series)
        with dpg.plot(label="Line Series", height=400, width=400, tag='plot'):
            dpg.add_plot_axis(dpg.mvXAxis, label="x", tag = "x_axis")
            dpg.add_plot_axis(dpg.mvYAxis, label="y", tag="y_axis")
            dpg.add_line_series(sindatax, sindatay, label="0.5 + 0.5 * sin(x)", parent="y_axis", tag="series_tag")
            

dpg.create_viewport(title='Custom Title', width=900, height=600)
dpg.setup_dearpygui()
dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()

```

**Comment by my1e5** [comment]
Can confirm I also get this issue. 
```
MacOSX 10.15.7
Python 3.10
xdialog                                           1.0.11.0
dearpygui                                         1.8.0
```
Here is a really simple example:
```python
# test.py
import dearpygui.dearpygui as dpg
import xdialog
dpg.create_context()

def info():
    xdialog.info()

with dpg.window():
    dpg.add_button(label="Show info", callback=info)
 
dpg.create_viewport()
dpg.setup_dearpygui()
dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()
```
When you click the button I get this error and the GUI crashes:
```bash
❯ python test.py
[1]    76201 illegal hardware instruction  python3 test.py
```

Interestingly, if you call an xdialog first before starting DPG, then the pop-up works. But then it crashes. And this time I get a `segmentation fault`.
```python
import dearpygui.dearpygui as dpg
import xdialog
dpg.create_context()

xdialog.info()

with dpg.window():
    pass
 
dpg.create_viewport()
dpg.setup_dearpygui()
dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()
```
Output: `[1]    76232 segmentation fault  python3 test.py`

**Comment by mathgeniuszach** [comment]
First of all, `xdialog.info()` on MacOS just calls [tkinter.messagebox.showinfo()](https://docs.python.org/3/library/tkinter.messagebox.html), so I would test that this is not an issue with tkinter first. A generic "segmentation" fault gives me no information about potential fixes.

As the info on the front page says, xdialog does not support native file dialogs on MacOS, because I do not have a Mac. Implementing native file dialogs would be appreciated.

**Comment by pwilliam123** [comment]
I found this for native MAC -> https://github.com/ninest/aquaui/

**Comment by my1e5** [comment]
@xMGZx Seems to happen  `open_file` as well
```python
def open_file():
    xdialog.open_file()

with dpg.window():
    dpg.add_button(label="Open file", callback=open_file)
```
gives me `illegal hardware instruction` - no other error message so hard to know what's happening.

**Comment by mathgeniuszach** [comment]
> I found this for native MAC -> https://github.com/ninest/aquaui/

Thank you for attempting to find something, but xdialog is meant to be portable even in places that do not allow for installing packages (i.e., it only uses the standard library). Thus I cannot use another package for native Mac dialogs.

**Comment by mathgeniuszach** [comment]
Please, for those who have Macs, let me know if this is a tkinter issue by replacing the specific line of code with the corresponding tkinter message box call.

**Comment by mathgeniuszach** [comment]
Ya'll just left me to dry here XD

**Comment by mathgeniuszach** [comment]
Closing this as there's nothing I can really do about this, other than implement proper MacOS support.
