### ISSUE TITLE
How to change the text size of output phrases?

### ISSUE THREAD

**Issue by tellts** [xMGZx/xdialog#11]
So that people who wear glasses due to poor eyesight can see the inscriptions better, where can I edit the settings for this?

**Comment by mathgeniuszach** [comment]
xdialog uses native dialogs on windows and linux (and tkinter on macos), and therefore does not offer options for font size or style customization. You'll probably have to change the compatibility options in the app or os respectively.

**Comment by tellts** [comment]
"You'll probably have to change the compatibility options in the app"
How can I do that?

**Comment by mathgeniuszach** [comment]
> ... app or os respectively

Application, OR Operating System. xdialog uses _native_ dialogs which means it's stuck with whatever styling and font size the operating system provides. Therefore, if you want to increase the font size, you'd have to do it system wide or within the compatibility options in whatever app's properties is using xdialog.
