### ISSUE TITLE
input

### ISSUE THREAD

**Issue by tellts** [xMGZx/xdialog#12]
I want to ask the user of the program different things and put it in a variable. What can you advise?

**Comment by mathgeniuszach** [comment]
xdialog is not a sophisticated dialog toolkit, and thus it does not offer this functionality currently. Depending on your use case you may find it more useful to use terminal input or a portion of a ui toolkit.

**Comment by tellts** [comment]
I found an easy way
>>> import pymsgbox
>>> pymsgbox.alert('This message!')
>>> user_response = pymsgbox.prompt('What is this??')

**Comment by mathgeniuszach** [comment]
Closing as not planned, as a windows native input dialog is too difficult to do this for. Effectively, something [like this function](https://github.com/haephrati/SGInputBox/blob/master/InputBox/SG_InputBox.cpp#L168) needs to be rewritten in python using ctypes.
