### ISSUE TITLE
Confirm Save As warning prompt missing when you type filename without extension

### ISSUE THREAD

**Issue by my1e5** [xMGZx/xdialog#4]
Consider this simple example:

```python
import xdialog
xdialog.save_file("Title Here", filetypes=[("Text File", "*.txt")])
```

![xdialog2](https://user-images.githubusercontent.com/10064103/182898205-24a9941d-dabc-4bcf-b6a1-07ddb18e0196.png)

I'm trying to save a text file but in this folder already exists a file called `foo.txt`. But if I type in foo and click 'Save' there is no 'Confirm Save As' warning prompt that a file called 'foo.txt' already exists. Note that the prompt does appear if I directly click the file in the selector and then click 'Save'. It's only when I type the name of the file myself that it doesn't work. 

![image](https://user-images.githubusercontent.com/10064103/182895245-2f8a2726-469f-4c12-ac97-be33666ed15e.png)

It's like it doesn't know that I'm trying to save `foo.txt` even though below it says 'Save as type:'. It just thinks I'm trying to save `foo` without an extension?

**Comment by mathgeniuszach** [comment]
First off, enable viewing file extensions on windows (You can do this by clicking the “View” tab on the ribbon followed by checking the “File name extensions” box). For some ridiculous reason, Windows doesn't show them by default, and it leaves you vulnerable to downloading and running a file like "Important Info.pdf.exe" (which, without file extensions shown you'll see "Important Info.pdf" and think it's safe to open).

Afterwards, try typing "foo.txt" into the box. That will likely cause the message to show up properly.

**Comment by mathgeniuszach** [comment]
Additionally, see what `save_file()` outputs. Does it output a path with `.txt` at the end or not? When does it do so?

**Comment by my1e5** [comment]
Yes typing `foo.txt` into the box does show the message to show up. If you just write `foo` then `save_file()` outputs `foo` without `.txt`. 

My issue is that from a users perspective it isn't clear that you need to type in the full filename including extension. It is more intuitive to just write `foo` given that below it says 'Save as type: Text File(*.txt)`. 

I want the user to be able to type in the filename without extension and then for xdialog to check based on the selected `Save as type` extension whether filename+extension is present and show the warning prompt.

**Comment by my1e5** [comment]
I think it's a Windows specific bug. Cause I just tried the same thing on Mac and it shows the Confirm Save As warning prompt when I type `foo` and `foo.txt` already exists in the directory. 

Also on Mac `xdialog.save_file()` returns `foo.txt` when I just type`foo` into the box.

**Comment by mathgeniuszach** [comment]
Mac relies on tkinter as a fallback and doesn't have native support. Don't use this library on Mac in environments where tk is not available. The file types filter normally only filter the files you can select, it doesn't normally impact which files you can save to. It is not a bug, this is just the base functionality.

Normally, people are smart enough to know they have to put `.txt` at the end of the file to have it save as a text file if they're running python scripts; nobody intentionally keeps file extensions off. On Linux, it never assumes the file extension (even if you select a type) and I don't even think I can implement it there. Ultimately, I don't think I'll implement a fix this. And even if I did, it probably wouldn't fix your issue with the confirm save as dialog.

**Comment by my1e5** [comment]
My use case is a DearPyGui app which is to be used by non-technical people (just basic MS Office knowledge). So it's very likely they won't know to add `.txt` to the end of the file name. 

If you look at other default Windows app such as Notepad, they do show a Confirm Save As prompt if you type the filename without an extension. 

![image](https://user-images.githubusercontent.com/10064103/183394992-57105bed-435b-4989-92f8-14bd2eb2fada.png)

So I feel for most users, we assume that Windows will do this check. 

In fact here is another example of this behavior with MS Word

![xdialog3](https://user-images.githubusercontent.com/10064103/183395706-4cdd6f88-7d4b-494e-9ffe-0c4a957f5fa6.png)

For now I can work around this issue by having a manual check, if `xdialog.save_file()` returns a filepath without a valid extension then it checks for a clashing filename and continues but if not it prompts the save file window again.

**Comment by mathgeniuszach** [comment]
Gonna be working on a potential solution to this. On my windows virtual machine, this is not fixed.

**Comment by xMGZx** [comment]
Fixed, seems the issue was actually a misconfigured python.
