### ISSUE TITLE
Fix for missing "Confirm Save As" prompt Windows

### ISSUE THREAD

**Issue by my1e5** [xMGZx/xdialog#5]
I did some further investigation into issue #4 and have found what I believe is the fix. For the `opts` parameter you need to set  `lpstrDefExt`. 

```python
# Filetypes
if filetypes:
    out = []
    for s, t in filetypes:
        out.append(f'{s} ({t})\0{";".join(t.split())}\0')
    opts.lpstrFilter = ''.join(out)+'\0' # Extra NULL byte just in case
    opts.lpstrDefExt = ''.join(out)+'\0' # Extra NULL byte just in case   
```

This makes the file save dialog box work perfectly. Depending on the selected default extension it will add the extension if not present, do the overwrite check, and it makes `xdialog.save_file()` return the filename with the extension attached. This brings it in line with the default behaviour of other Windows save dialog boxes. I think it would be a worthwhile addition. 

For reference, I gathered the info to work this out using https://gist.github.com/nicomgd/1097a0b7ca3715da4e71

**Comment by mathgeniuszach** [comment]
The MS documentation seems to imply that lpstrDefExt is a single extension that applies in all cases, based on what you're saying it's actually different per the extension you select?

**Comment by my1e5** [comment]
Yes I've just tested it with multiple filetypes
```python
import xdialog
filename = xdialog.save_file("Title Here", filetypes=[("Text", "*.txt"),("CSV", "*.csv")])
print(filename)
```
The 'Confirm Save As' prompt works correctly for all filetypes. You can change filetype and it will do the correct check to see whether the file exists (even when you omit the extension from the filename). And it will return the filename with the correct extension attached if you didn't type it.
