### ISSUE TITLE
ValueError: embedded null character

### ISSUE THREAD

**Issue by IvanNazaruk** [xMGZx/xdialog#9]
Python: 3.7.15 x64
xdialog: 1.0.10.0
## Error msg:
```
  File "C:\ProgramData\Miniconda3\envs\test3.7\lib\site-packages\xdialog\__init__.py", line 66, in open_file
    return dialogs.open_file(title, filetypes, multiple)
  File "C:\ProgramData\Miniconda3\envs\test3.7\lib\site-packages\xdialog\windows_dialogs.py", line 53, in open_file
    opts.lpstrFilter = ''.join(out)+'\0' # Extra NULL byte just in case
ValueError: embedded null character
```
I tried to solve this problem myself using the solution from here:
https://github.com/arsenetar/send2trash/issues/17
https://github.com/arsenetar/send2trash/pull/18/commits/213417d3f2562f0dd5c9e11bdca272b6fb355fed
And I was able to fix it, but it looks pretty rough and only for this function (`xdialog.dialogs.open_file`).

**Comment by mathgeniuszach** [comment]
This is kinda dumb, but alright lol, thanks for providing a solution

**Comment by mathgeniuszach** [comment]
Fixed by https://github.com/xMGZx/xdialog/commit/c4e13fad294b3a054e8fe5294d03e1146108169a
